name: Test Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Run Python Script
        env:
          BAKA_USERNAME: ${{ secrets.USERNAME }}
          BAKA_PASSWORD: ${{ secrets.PASSWORD }}
          SCHOOL_DATA: ${{ secrets.DATA }}
        run: uv run -m tests.test_logging